### ISSUE TITLE
--squash is only supported on a Docker daemon with experimental

### ISSUE THREAD

**Issue by bminossi** [GouveaHeitor/uranus#1]
First of all, congratulations for your project =-).
I really appreciate the fact that you'r sharing with our sec community.
I'm doing just a report about the installation process that some users could be confused.
Maybe when users execute the setup.sh file, docker will be warning: 
"--squash" is only supported on a Docker daemon with experimental features enabled

We can put docker in experimental configuration using this command bellow:
echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json

Maybe would be nice certify that this mode is enabled during the installation =-)
Thanks

**Comment by GouveaHeitor** [comment]
Hi @bminossi, 
I'm sorry for the delay in replying, I ended up getting lost in the notifications...
I will update the repository with your suggestions, thank you very much!
